name: sendotp_flutter_sdk
description: "Send OTP SDK for Flutter application."
version: 0.0.1
homepage: https://msg91.com/in/otp
repository: https://github.com/Walkover-Web-Solution/SendOTP-flutter-SDK?tab=License-1-ov-file#readme 

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

